development:
  adapter: postgresql
  database: subscription_tracker_development
  username: rclements
  #host: localhost
  pool: 5
  port: 5432

test:
  adapter: postgresql
  database: subscription_tracker_test
  username: rclements
  #host: localhost
  pool: 5
  port: 5432

production:
  adapter: postgresql
  database: subscription_tracker_production
  username:
  password:

